### ISSUE TITLE
Docker isntall failure when re-creating sirepo-dev vm

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#125]
I had to recreate a vm recently. That when fine but when I tried to install docker (`radia_run redhat-docker`) I ran into [this error](https://github.com/radiasoft/download/blob/master/installers/redhat-docker/radiasoft-download.sh#L54)
```
physical volume /dev/sdb already initialized, cannot install docker
```
My guess that the cause of this was my old v-docker.vdi not being deleted up properly and causing issues with the new docker install. Doing a `vagrant destroy`, removing v-docker.vd, and doing a new install cleaned up the issue.

There is code to delete an existing vdi when doing `radia_run vagrant-sirepo-dev`. Maybe it doesn't work right.

**Comment by robnagler** [comment]
We removed the docker disk so not an issue.
