### ISSUE TITLE
Update OPAL to 2.4.0

### ISSUE THREAD

**Issue by cchall** [radiasoft/download#129]
There was a major change in 2.4 to an existing feature in OPAL I may need for a new project. It would be ideal to be on the latest version for this work.

**Comment by robnagler** [comment]
This is built. If you have a VM, you can "sudo dnf update -y". 

An alpha release is happening for jupyter now.

**Comment by cchall** [comment]
Was this released to alpha Jupyter? I just tried restarting and still see Version 2.2.0.

**Comment by robnagler** [comment]
Yes, now, and on beta, which is easier to use (not throttled like alpha).

There was an alpha release when I wrote this, but for some reason it didn't include opal 2.4.
