### ISSUE TITLE
CYGWIN_NT-10.0 is an unsupported system,

### ISSUE THREAD

**Issue by bruhwiler** [radiasoft/download#14]
With a fresh install of Cygwin (2016.03.05) on Windows 10 Pro, the command

> curl radia.run | bash
> generates the following error message:
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   204  100   204    0     0    236      0 --:--:-- --:--:-- --:--:--   311
> CYGWIN_NT-10.0 is an unsupported system, sorry
> If you don't know what to do, please contact support@radiasoft.net.

**Comment by robnagler** [comment]
Did you buy Radia Run® Gold Pro Enterprise Edition? I don't think it will
work without the license key.

**Comment by robnagler** [comment]
I don't think we can support cygwin at this time, and users haven't requested it. Better to support bash on native windows.
