### ISSUE TITLE
install_repo foo/bar doesn't implicitly call bar_main

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#154]
Uses install_url which ends with contents so tries to find contents_main.

**Comment by e-carlin** [comment]
Wrong issue. Should have been #164

**Comment by e-carlin** [comment]
Running into this when trying to call `radia_run radiasoft/raydata`

**Comment by robnagler** [comment]
what does debug show?

**Comment by e-carlin** [comment]
What you said in the opening comment. It tries to call `content_main`. I'll dig in and find a way to get it to call $repo_name_main.

**Comment by robnagler** [comment]
It's kind of tricky. Could have special parsing for this case (if github.*contents, then strip contents, too).

**Comment by robnagler** [comment]
Fixed, I think.
