### ISSUE TITLE
add credentials for cloning private git repo

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#157]
We'll need creds to clone rsflash when building. See https://github.com/radiasoft/rsflash/issues/2#issuecomment-796991810

**Comment by robnagler** [comment]
Another alternative is to clone rsflash into guest_d before running docker. Not sure which is easier.

**Comment by e-carlin** [comment]
We've decided to move all proprietary data currently in rsflash into sirepoflash and make rsflash  (python) publicly available.
