### ISSUE TITLE
Difficulty buiding/running PyZgoubi

### ISSUE THREAD

**Issue by dtabell** [radiasoft/download#164]
The original PyZgoubi was Python 2, which is officially deprecated. The latest version on GitHub (https://github.com/PyZgoubi/PyZgoubi) has been updated to Python 3.7 or newer. I built it on Jupyter, but have not succeeded in getting it to run. After following the simple build instructions, `./setup install`, I get an error when I try `pyzgoubi --version`:
```
jupyter> pyzgoubi --version
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/pyzgoubi", line 4, in <module>
    __import__('pkg_resources').run_script('pyzgoubi==0.8.0a1', 'pyzgoubi')
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1436, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/pyzgoubi' not found in metadata at '/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pyzgoubi-0.8.0a1.dist-info'
```

**Comment by robnagler** [comment]
@e-carlin this is needed for USPAS so please see if you can figure it out today.  I can help if you are stuck

**Comment by e-carlin** [comment]
@dtabell I got it working by doing this:
```sh
# cd to where you cloned PyZgoubi
$> pip install -e .
$> pip install zgoubi_metadata
$> pyzgoubi --version
# Version output
```

Does that work for you?

**Comment by robnagler** [comment]
@dtabell do you want this added to the docker image?

**Comment by dtabell** [comment]
I will test Evan’s suggestion and let you know sometime today.

**Comment by dtabell** [comment]
Yes, please.

**Comment by robnagler** [comment]
@e-carlin put in beamsim-jupyter. @moellep please release alpha and beta asap. We'll run prod on Thu before USPAS. I'll be restarting all servers on Sat or Sun.

**Comment by dtabell** [comment]
Some weirdness:
The file `zgoubi/gcp.py` in my cloned version of PyZgoubi/ differs from that in
`/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/zgoubi/gcp.py`
The latter is most definitely not Python 3, while the former is.
Is it reasonable to assume this problem will go away after the restart?

**Comment by e-carlin** [comment]
@dtabell what environment (alpha, beta, or prod) is that happening on? We've only pushed the new pyzgoubi through beta. It will reach prod on Thursday.
