### ISSUE TITLE
Update to OPAL 2021.1

### ISSUE THREAD

**Issue by cchall** [radiasoft/download#183]
It would be nice to update to OPAL 2021.1. 
There is a (long awaited) update to monitor output file information that should allow for dumping significantly smaller files in many cases.

**Comment by j-edelen** [comment]
@e-carlin, can this be prioritized over the next couple of days? This can be charged to fastfelo.

**Comment by e-carlin** [comment]
Yes, will aim to get it done by end of the week so it can be deployed next week.

**Comment by robnagler** [comment]
I'm building. This will get in an alpha release next Tue and on prod on Mon 1/17.

**Comment by cchall** [comment]
@robnagler we're now going to need the new, optional MITHRA dependency installed as well (see [here](https://gitlab.psi.ch/OPAL/build-recipes/-/blob/master/240-build-MITHRA) for opal developer install script). 

Sorry I didn't mention this sooner.

**Comment by e-carlin** [comment]
I'll add https://github.com/radiasoft/download/issues/190
