### ISSUE TITLE
Packages are dropping support for py37

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#188]
The latest numpy (1.22.0) dropped support for py37 https://github.com/numpy/numpy/releases/tag/v1.22.0

According to pypi 1.22.0 is what is currently the latest but installing from pip yields different results
```
numpy (main)$ pip install numpy==1.22.0
ERROR: Could not find a version that satisfies the requirement numpy==1.22.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, \
1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.\
15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18\
.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0rc1, 1.20.0rc2, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0rc1, 1.21.0rc2, 1.21.0, 1.21.1, 1.21.2\
, 1.21.3, 1.21.4, 1.21.5)
ERROR: No matching distribution found for numpy==1.22.0
```

**Comment by e-carlin** [comment]
Should we pin numpy or upgrade python?

We have other issue(s?) regarding pinning numpy https://github.com/radiasoft/download/issues/123

I seem to recall versions after py37 changed some async behavior. Need to refresh my memory...

**Comment by robnagler** [comment]
I think we should consider upgrading Python. I think the CancelledError or whatever is the only thing we know that won't work. Would you try in your dev env?

**Comment by e-carlin** [comment]
Sure. pyenv 3.10:latest is 3.10.1rc1. Probably close enough to 3.10.1 for our purposes...

**Comment by e-carlin** [comment]
Bump scipy too https://github.com/scipy/scipy/blame/fdc31f3d2bfa90a2c214a398668f0e153632d2bb/setup.py#L454
