### ISSUE TITLE
opal: add MITHRA

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#190]
@cchall says:
> @robnagler we're now going to need the new, optional MITHRA dependency installed as well (see here for opal developer install script).
> Sorry I didn't mention this sooner.

**Comment by e-carlin** [comment]
@cchall I have the build working. Do you have an example that utilizes mithra so I can make sure everything works together?

**Comment by cchall** [comment]
@e-carlin we don't have any input files of our own yet so the best I can probably offer is what is from opal's regression tests: https://gitlab.psi.ch/OPAL/regression-tests/-/blob/master/RegressionTests/UndulatorAWA/UndulatorAWA.in

**Comment by e-carlin** [comment]
Thank @cchall. That lead to some MPI errors

```
Fatal error in PMPI_Allreduce: Invalid buffer pointer, error stack:
PMPI_Allreduce(450): MPI_Allreduce(sbuf=0x7fff9b6b33d0, rbuf=0x7fff9b6b33d0, count=1, datatype=MPI_DOUBLE, op=MPI_MIN, comm=MPI_COMM_WORLD) failed
PMPI_Allreduce(409): Buffers must not be aliased
```

I'm not familiar with that error and PSI Gitlab is down which is making it hard to debug. I'll troubleshoot next week.

**Comment by e-carlin** [comment]
Just noting for my future self - In MPI one can use the same send and receive buffers. This is done using `MPI_IN_PLACE`. For example, [here is opal using it](https://gitlab.psi.ch/OPAL/src/-/commit/662ad80fdf920c202d6956be77c08de2e4c89594#b2a4d32701bffac6b4f56d3733b98b7900b2b333_496_504). For a still unclear reason to me this results in the above error on my vm. But running inside of sirepo docker container it worked. 

More info on MPI_INPLACE: https://www.rookiehpc.com/mpi/docs/mpi_in_place.php

**Comment by cchall** [comment]
@e-carlin was the MPI error resolved? I think I'm seeing the same thing when I try to run UndulatorAWA.in on alpha.

**Comment by e-carlin** [comment]
Kind of... I still had the error on my vm but running inside of docker the error went away. So, I thought it was just some problem (ex messed up configuration) on my vm. Seems that isn't the case. If you don't mind please open a new issue with details on the error and a test case and I'll troubleshoot.
