### ISSUE TITLE
Failed to install vagrant-sirepo-dev

### ISSUE THREAD

**Issue by mrakitin** [radiasoft/download#21]
@kalebswartz7 and I were trying to install the `vagrant-sirepo-dev` machine using the instructions at https://github.com/radiasoft/sirepo/wiki/Development#mac-install, but it failed multiple times on independent machines with the following error:

```bash
warning: /var/cache/dnf/docker-ce-stable-8cf73e63b8c72e93/packages/docker-ce-18.03.1.ce-1.fc27.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
neverallow check failed at /var/lib/selinux/targeted/tmp/modules/100/base/cil:8988
  (neverallow base_typeattr_7 unlabeled_t (file (entrypoint)))
    <root>
    allow at /var/lib/selinux/targeted/tmp/modules/200/container/cil:1489
      (allow spc_t unlabeled_t (file (entrypoint)))
    <root>
    allow at /var/lib/selinux/targeted/tmp/modules/100/sandboxX/cil:840
      (allow sandbox_x_domain exec_type (file (entrypoint)))
    <root>
    allow at /var/lib/selinux/targeted/tmp/modules/100/virt/cil:1664
      (allow virtd_lxc_t exec_type (file (entrypoint)))
    <root>
    allow at /var/lib/selinux/targeted/tmp/modules/100/virt/cil:2055
      (allow svirt_sandbox_domain exec_type (file (entrypoint)))

Failed to generate binary
/usr/sbin/semodule:  Failed!
Error accessing specified device /dev/mapper/docker-vps: No such file or directory
```

Another issue is in the beginning:
```
==> default: Running provisioner: shell...
    default: Running: inline script
cat: write error: Broken pipe
Can't remove /etc/selinux/config: Permission denied, skipping file.
```

The first problem is critical, and probably is related to the second issue. Please help us to resolve the issue. Thanks!

attn @robnagler

**Comment by mrakitin** [comment]
Here is the full installation log: [vagrant.log](https://github.com/radiasoft/download/files/2172088/vagrant.log)

**Comment by robnagler** [comment]
You can ignore the selinux errors. The real problem is the docker-vps not being there, which seems to be a bug in vagrant-persistent-storage. I need to look into this, because it may be related to selinux being turned off.

I turned off the docker install if /dev/mapper/docker-vps does not exist. This might help.

**Comment by robnagler** [comment]
I also removed the selinux disabling (required for docker) so that may help, too.

Try again.

**Comment by robnagler** [comment]
I got a clean install. 

I did have issues with VirtualBox, which required an upgrade to both VB and Vagrant so I recommend you do that.

**Comment by mrakitin** [comment]
Thanks @robnagler! It went further after your fixes, however I got this error during sirepo installation:
```
Installing collected packages: pykern
  Running setup.py develop for pykern
Successfully installed pykern
From https://github.com/radiasoft/sirepo
   9a86869e..dad93aad  master     -> origin/master
   59234dfd..5713e89b  robnagler  -> origin/robnagler
Already up-to-date.
Obtaining file:///home/vagrant/src/radiasoft/sirepo
    Complete output from command python setup.py egg_info:
    error in sirepo setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'+git://g'"

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/vagrant/src/radiasoft/sirepo/
2018-07-07T21:48:59Z install_main
Unexpected error; Install failed.
If you don't know what to do, please contact support@radiasoft.net.
2018-07-07T21:39:21Z install_main
Unexpected error; Install failed.
If you don't know what to do, please contact support@radiasoft.net.
```

**Comment by mrakitin** [comment]
I think I understood the problem. The reason was that this VM somehow mounted my local ~/src/radiasoft/sirepo/ folder, which was on an older branch. Can it be optionally configured so that it had a local copy, not a mounted one?

**Comment by robnagler** [comment]
Yes, this is optional:

```sh
curl radia.run | vagrant_dev_no_nfs_src=1 bash -s vagrant-sirepo-dev
```

The flag isn't the best and isn't documented, because I didn't think people would be using it much.

**Comment by mrakitin** [comment]
OK, thanks @robnagler! Closing for now since the issue with the installation is resolved.

**Comment by robnagler** [comment]
BTW, I isolated the docker install into: radia_run redhat-docker.  It will be needed for sirepo-dev eventually, but easier if it is a separate installer now.
