### ISSUE TITLE
enable pymoab with openmc

### ISSUE THREAD

**Issue by moellep** [radiasoft/download#222]
Please add the "-D ENABLE_PYMOAB=ON" flag when building openmc.sh

https://github.com/radiasoft/download/blob/97b44bee41b6cd0805b7a1f7e429601afec061c2/installers/rpm-code/codes/openmc.sh#L23

**Comment by moellep** [comment]
Checking if the priority on this one could get bumped up. It would be very useful to have access to pymoab for sirepo.

**Comment by e-carlin** [comment]
Sorry for the delay. Will do tomorrow.

**Comment by moellep** [comment]
Great! Also, could you check after it is built that this import works OK:
```python
import openmc
import openmc.lib
import pymoab
```
Currently it complains on the openmc.lib import with:
```
OSError: /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/openmc/lib/libopenmc.so: cannot open shared object file: No such file or directory
```

**Comment by moellep** [comment]
Additional notes from Mike on this issue: https://github.com/radiasoft/prop22_cloudmc/issues/11#issuecomment-1196993920

In my local vm, I had to take these steps:

1. clone the [openmc repository](https://github.com/openmc-dev/openmc)
2. sudo dnf install openmpi
3. module load mpi/openmpi-x86_64
4. cd <openmc dir from the clone above>
5. mkdir build
6. cd build
7. cmake -DOPENMC_USE_MPI=ON ..
8. make
9. cp lib/libopenmc.so ~/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/openmc/lib/
