### ISSUE TITLE
dev-build all codes

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#248]
- [x] common
- [x] genesis
- [x] pydot
- [x] boost
- [x] ml
- [x] rsbeams
- [x] fnal_chef
- [x] synergia
- [x] jspec
- [x] bnlcrl
- [x] srw
- [x] radia
- [x] ipykernel
- [x] bluesky
- [x] elegant
- [x] epics
- [x] hypre
- [x] h5hut
- [x] parmetis
- [x] metis
- [x] trilinos
- [x] opal
- [x] openmc
- [x] petsc
- [x] slepc
- [x] ~~petsc4py~~ # Now part of rscode-petsc
- [x] ~~slepc4py~~ # Now part of rscode-slepc
- [x] fenics
- [x] pydicom
- [x] pymesh
- [x] forthon
- [x] openpmd
- [x] pygist
- [x] warp
- [x] ~~libgfortran4~~ # not needed by shadow3
- [x] xraylib
- [x] shadow3
- [x] pyzgoubi
- [x] zgoubi
- [x] mgis

**Comment by e-carlin** [comment]
All codes are building. Once https://github.com/radiasoft/download/issues/340 is addressed I'll open a PR.

**Comment by e-carlin** [comment]
All codes built succesfully
