### ISSUE TITLE
elegant & epics Can't locate FindBin.pm 

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#250]
```txt
Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /usr/local/lib64/perl5/5.34 /usr/local/share/perl5/5.34 /usr/lib64/perl5/vendor_pe\
rl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at ../../../src/tools/convertRelease.pl line 22.
BEGIN failed--compilation aborted at ../../../src/tools/convertRelease.pl line 22.
```

**Comment by e-carlin** [comment]
This used to be distributed through perl-interpreter which came with fedora. But, it is no longer in perl-interpreter so it should be installed manually.

**Comment by robnagler** [comment]
Might be a in an rpm available from Fedora, but maybe not... Could always just install it directly with elegant.sh for the build.

**Comment by e-carlin** [comment]
Thanks. There is an rpm for just it `perl-FindBin` . I added it to common because both epics and elegant need it.
