### ISSUE TITLE
silas failing with missing rsmath

### ISSUE THREAD

**Issue by moellep** [radiasoft/download#258]
The silas "Two Mirrors" examples is failing with the error:
```
ModuleNotFoundError: No module named 'rsmath'
```

**Comment by e-carlin** [comment]
@robnagler what's the proper fix here
1. Add rsmath to rscode-rsbeams?
2. Add rsmath to [rslaser deps](https://github.com/radiasoft/rslaser/blob/b65afe417fc2887ec5a6bde6322c3546268fc031/setup.py#L15)

Both?

**Comment by robnagler** [comment]
Unfortunately we can't add pypi packages to setup.py files until we start pushing everything to pypi. We could add a git dependency, perhaps. What do you think?

**Comment by e-carlin** [comment]
I think a git dep is good. I'll open a PR.

**Comment by e-carlin** [comment]
This was fixed some time ago.
