### ISSUE TITLE
sirepo-ci-build installer

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#262]
This will run as root (assert) and do the following:

1. cd ~/src/radiasoft
1. gcl container-beamsim
1. build beamsim without a push
1. gcl container-sirepo-ci 
1. build sirepo-ci without a push -- make sure that beamsim:latest is used as base
1. run sirepo-ci:
    1. install pykern 
    1. pykern ci run -- emulate sirepo-ci-pull-action possibly
    1. install sirepo
    1. run sirepo/test.sh -- not with sirepo-ci-pull-action
1. tag and push beamsim
1. tag and push sirepo-ci

This is designed to run on the build server where there is already a ~/src/radiasoft, but it can be tested on any VM.

**Comment by rorour** [comment]
What is sirepo-ci-action? And why are we doing both pykern ci run and test.sh?

**Comment by robnagler** [comment]
> What is sirepo-ci-action?

sirepo-ci-pull-action (fixed above)

> And why are we doing both pykern ci run and test.sh?

One is on pykern and the other is on sirepo.

**Comment by rorour** [comment]
Thanks, I'm still not sure what sirepo-ci-pull-action is though. Do you mean to copy these lines from ci-pull-request?
```
            if [[ -f test.sh ]]; then
                bash test.sh
            else
                pykern ci run
            fi
```

**Comment by rorour** [comment]
Ok, I'm still unclear what you mean by "pykern ci run -- emulate ci-pull-request possibly" and "run sirepo/test.sh -- not with ci-pull-request." What do you want me to do aside from `pykern ci run` in pykern and `bash test.sh` in sirepo?

**Comment by robnagler** [comment]
"possibly" means experimental. Something like this:

```sh
docker run [flags] radiasoft/sirepo-ci <<EOF
source ~/.bashrc
mkdir -p ~/src/radiasoft
cd ~/src/radiasoft
pip uninstall pykern
gcl pykern
cd pykern
pip install -e .
pykern ci run
cd ..
gcl sirepo
cd sirepo
pip install -e .
bash test.sh
EOF
```
