### ISSUE TITLE
Wiki explaining installer architecture                               

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#272]
- simple server so don't need special permissions and pulls from github in production
- what happens before an installer is run
- what are the parameters you can change from the command line
- how does a script get run
- how are variables cascaded inside subshells, docker etc.
- how to call other installers (note: discussion here between install_repo and install_repo_eval -- not sure myself what should be default)
- how to debug
- explain other functions in install.sh that are useful
- ??

**Comment by rorour** [comment]
What project should I charge this to?

**Comment by rorour** [comment]
@robnagler I just added what I had done to the wiki. If you'd like me to continue working on this I can. https://github.com/radiasoft/download/wiki/Installer-Architecture

**Comment by robnagler** [comment]
I made some changes and added some comments for changes. Please update.

**Comment by rorour** [comment]
What exactly do you have in mind when you ask "how do you write an installer?"  The answer that I'm coming up with seems too literal- make a bash script called radiasoft-download.sh, create a main function.

Also, I don't know how to further answer "what's the purpose of an installer?". In your comment you wrote "simple server so don't need special permissions and pulls from github in production". I think the first section (which I just renamed to Purpose of Installers) covers that, plus "Installers are used to download and install Docker images". What more should I add?

**Comment by robnagler** [comment]
> What exactly do you have in mind when you ask "how do you write an installer?" The answer that I'm coming up with seems too literal- make a bash script called radiasoft-download.sh, create a main function.

I was speaking to the order list of things that happen in an installer. Rather, the purpose of an installer is to allow you to run a script dynamically on any computer that has curl and bash. Usually this is to add new packages or configuration to an existing computer or virtual machine. 

Installers can depend on other installers so they modular. They can take arguments and environment variables. (Talk about the tradeoff between them.) Installers can have auxiliary files that can be downloaded incrementally.

As to how you write an installer, there are choices to make. It can be in its own repo (e.g. radiasoft/jupyter.radiasoft.org) or in download/installers. These are tradeoffs. Once that decision is made, you need to decide what the installer might need and how it will get those things (parameters, files, packages, etc.). 

I would guide the user through a simple problem (pick an existing installer). Walk then through the design choices.

**Comment by rorour** [comment]
Why would you put an installer in its own repo vs in download?

**Comment by robnagler** [comment]
Modularlization of the installer so that you don't distribute knowledge or to allow other orgs (biviosoftware) to create installers who don't have access download/installers. There's a tradeoff with "mono repo" vs modularized repos. I'm sure you can find a debate on the web about lots of small, independent repos/packages vs having big packages.

**Comment by rorour** [comment]
Thanks. I added more to the wiki. 

Is there something specific about this repo that I should add on the topic of debugging?

**Comment by robnagler** [comment]
This needs to be filled out more. For example, 

```markdown
Parameters that can be changed from the command line:

- alpha/beta/dev/prod: sets $install_channel to the channel passed
- debug: sets $install_debug and $install_verbose to 1
- quiet: sets $install_debug and $install_verbose to an empty string
- verbose: sets $install_verbose to 1
```

You need to describe the types of output: verbose, debug, or normal. Since this is architecture, explain how different output is generated. You can also set parameters as environment variables. It's not important that values are "1" or "empty string", but rather they are "on" or "off", e.g. debug can be supplied on the command line before the installer name, and it will turn on debug output which includes a complete trace of all shell commands (i.e. `set -x` is called).

Try to create more explanations like that.

**Comment by rorour** [comment]
What is the reason for having both `install_repo()` and `install_repo_eval()`? `install_repo_eval` preserves PWD while `install_repo` might leave us in some other directory, which seems sloppy. `install_repo` is rarely used (I think 3 times in our codebase, and I don't see we couldn't use `install_repo_eval` in those cases). 

Also, what is the origin of the name `install_repo_eval`? I thought there might be some connection to the bash command `eval` but I don't see it.

**Comment by robnagler** [comment]
Thanks for the thorough research. All good questions/points.

I thought install_repo ran as a subshell, but it doesn't so you are right about install_repo_eval replacing install_repo everywhere. We should rename install_repo to something install_repo_internal so that we don't use it anyway. 

The original idea was that install_repo_eval would run in the current shell.  It was added in 569c8238d36d729e6edd244cdaaf54420d22216f, and it seems like it should always be used for install_repo_eval. I think there was some code at the time that required you to call install_repo by setting up variables and then running in a subshell. 

We could rename it. I'm not attached.

**Comment by rorour** [comment]
I think the wiki is ready for another review. https://github.com/radiasoft/download/wiki/Installer-Architecture

**Comment by robnagler** [comment]
I made a few more comments and some changes.

**Comment by rorour** [comment]
Thanks, I made the changes from your comments.

**Comment by rorour** [comment]
Is there more work you'd like me to do on this?

**Comment by robnagler** [comment]
done
