### ISSUE TITLE
openmc: correct HDF5_INCLUE_DIR and determine if IS_PARALLEL should be TRUE

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#311]
While building openmc I saw
```
-- Could NOT find HDF5 (missing: HDF5_DIR)
-- ---   HDF5 Configuration ::
--         IS_PARALLEL  : FALSE
--         INCLUDES     : /home/vagrant/.local
--         LIBRARIES    : /usr/lib64/mpich/lib/libhdf5hl_fortran.so;/usr/lib64/mpich/lib/libhdf5_fortran.so;/usr/lib64/mpich/lib/libhdf5_hl.so;/usr/lib64/mpich/lib/libhdf5.so\
;/lib64/libdl.so;/lib64/libsz.so;/lib64/libz.so;/lib64/libm.so
```

INCLUDES should be /usr/include since we install hdf5 from fedora repos.

I would guess IS_PARALLEL should be TRUE since we install hdf5-mpich. @robnagler can you comment? Would you guess that our hdf5 install is configured to be able to run in parallel?

**Comment by e-carlin** [comment]
Looking at the [cmake file](https://bitbucket.org/fathomteam/moab/src/e6a23a793c5f140f12928c64c5ab57fac5b85bb6/config/FindHDF5_MOAB.cmake#lines-129) for moab it uses  this block to determine if IS_PARALLEL
```
        set( HDF5_IS_PARALLEL FALSE )
        foreach( _dir IN LISTS HDF5_INCLUDE_DIR )
          if( EXISTS "${_dir}/H5pubconf.h" )
            file( STRINGS "${_dir}/H5pubconf.h"
              HDF5_HAVE_PARALLEL_DEFINE
              REGEX "HAVE_PARALLEL 1" )
            if( HDF5_HAVE_PARALLEL_DEFINE )
              set( HDF5_IS_PARALLEL TRUE )
            endif()
          endif()
          set(HDF5_IS_PARALLEL ${HDF5_IS_PARALLEL} CACHE BOOL
            "HDF5 library compiled with parallel IO support" )
          mark_as_advanced( HDF5_IS_PARALLEL )
        endforeach()
```

We don't have H5pubconf.h we have H5pubconf-64.h. So that will need to be fixed. But looking in that file I see
```c
/* Define if we have parallel support */
/* #undef H5_HAVE_PARALLEL */
```

This leads me to believe our HDF is not parallel. I'm a little confused since we install the mpich version of hdf5 which I thought would be for parallel support.

**Comment by robnagler** [comment]
I think you might need mpicc to get the parallel version, but I don't know how that relates to openmc. Rarely do codes write in parallel.

**Comment by sjcrs** [comment]
OpenMC is embarrassingly parallel, in that it will run independent particle histories on as many cores as you will give it. I would believe that each of these could be writing their results simultaneously. 

It looks like parallel hdf5 is an option: https://docs.openmc.org/en/stable/usersguide/install.html#prerequisites

**Comment by e-carlin** [comment]
Thanks for the info. Turns out I just needed to specify the write compiler which will pass on the correct flags to find parallel hdf5. Fix coming shortly.
