### ISSUE TITLE
vagrant ssh error

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#313]
I ran `vagrant-rsconf-dev` on centos. My guess is this is due to the change to direct `vagrant ssh`. 
```
+ vagrant ssh sudo su -
The machine with the name 'sudo' was not found configured for
this Vagrant environment.
+ install_err_trap
```

**Comment by e-carlin** [comment]
i'll fix because i need it for other work

**Comment by robnagler** [comment]
I fixed this on 229-docker-disk, and will issue a pull shortly
