### ISSUE TITLE
synergia boost undefined refs

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#331]
Tons of these

 undefined reference to `boost::python::converter::registry::insert

**Comment by e-carlin** [comment]
I think these were from the common you were using (which contains boost) being built on f32. I'm not seeing these in my system.

**Comment by e-carlin** [comment]
Boost is not in common. But still maybe some issue with common on f32. We'll see if they crop up again.

**Comment by robnagler** [comment]
Great!!! With enough eyes...
