### ISSUE TITLE
vagrant-dev add networks.conf to host

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#337]
I recently updated to Monterey and had to re-create my development vm. After creation I couldn't access the server running in my vm. Updating vbox (6.1.38) and vagrant (2.3.0) to the latest version as of writing. As well as adding adding a [networks.conf](https://www.virtualbox.org/manual/ch06.html#network_hostonly) to my host got things working.

**Comment by robnagler** [comment]
https://github.com/radiasoft/devops/issues/241

**Comment by robnagler** [comment]
I think it still needs to be added.

**Comment by robnagler** [comment]
vm_devbox
