### ISSUE TITLE
warp not py3 compatible

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#345]
Many non print_function prints. Could be other problems too. https://bitbucket.org/radiasoft/warp/src/4ebb54f21373d41b8b1abe2f7a6011896324907f/scripts/warpexample.py#lines-250

@robnagler when I try to compile warp for f36 and f32 it fails with errors about py 2 vs 3 problems. Looking at the f32 rscode-warp on depot I see that the prints are using print_function. Any clue how the code got in that state? Nothing in warp.sh looks to be converting it...

**Comment by robnagler** [comment]
This commit https://bitbucket.org/radiasoft/warp/commits/875a3007b386adc431eba7e2a1e7216d59f99d02

We are building from this commit: https://bitbucket.org/radiasoft/warp/commits/4ebb54f21373d41b8b1abe2f7a6011896324907f

Unless somebody forced the git history this commit should work

**Comment by e-carlin** [comment]
Can you elaborate more? I see non print_function prints in both https://bitbucket.org/radiasoft/warp/commits/875a3007b386adc431eba7e2a1e7216d59f99d02 (in the diff) and https://bitbucket.org/radiasoft/warp/commits/4ebb54f21373d41b8b1abe2f7a6011896324907f (see scripts/warpexample.py)

Maybe I run py2to3 over https://bitbucket.org/radiasoft/warp/commits/4ebb54f21373d41b8b1abe2f7a6011896324907f ?

**Comment by robnagler** [comment]
Those scripts aren't installed so they don't matter. Even if they are, they aren't used in Sirepo.

**Comment by e-carlin** [comment]
They are installed
```
tmp# dnf download rscode-warp
RadiaSoft fedora/32/x86_64 dev                                                                                                                                            44 kB/s | 2.9 kB     00:00
rscode-warp-20201231.175726-1.x86_64.rpm                                                                                                                                  35 MB/s |  14 MB     00:00
tmp# rpm -qlp rscode-warp-20201231.175726-1.x86_64.rpm | grep warpexample.py
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/warp/warpexample.py
```

Even if they aren't used in Sirepo they break the build of the rpm

Also, those prints were just examples. There are many others
```
warp ((HEAD detached at 4ebb54f2))$ gpy 'print '  | wc -l
1265
```

Some in files we do use
```
init_tools ((HEAD detached at 4ebb54f2))$ grep -r init_tools ~/src/radiasoft/sirepo/sirepo/package_data/template/warppba/
/home/vagrant/src/radiasoft/sirepo/sirepo/package_data/template/warppba/parameters.py.jinja:from warp.init_tools import *
init_tools ((HEAD detached at 4ebb54f2))$ grep -r 'print ' ~/src/radiasoft/warp/scripts/init_tools/
/home/vagrant/src/radiasoft/warp/scripts/init_tools/laser_tools.py:    print "================================================"
/home/vagrant/src/radiasoft/warp/scripts/init_tools/laser_tools.py:    print " Retropropagation completed."
/home/vagrant/src/radiasoft/warp/scripts/init_tools/laser_tools.py:    print "================================================"
/home/vagrant/src/radiasoft/warp/scripts/init_tools/generic_tools.py:                print 'Removing previous directory %s' %directory
```

**Comment by robnagler** [comment]
I just ran the build on fedora32 (py3). I saw this error(warning):

```txt
touch build3parallel/em3dparallelpydep
python setup.py -F gfortran --fcompexec mpifort --fcompexec mpifort --parallel build --build-base build3parallel install
gfortran: error: unrecognized command-line option ‘--showme:link’
running build
running build_ext
```

The build failed much later here:

```txt
byte-compiling /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warpoptions/__init__.py to __init__.cpython-37.pyc
byte-compiling /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp_parallel/__init__.py to __init__.cpython-37.pyc
running install_egg_info
Removing /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp-4.5-py3.7.egg-info
Writing /home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/warp-4.5-py3.7.egg-info
make[1]: Leaving directory '/home/vagrant/src/radiasoft/codes/warp-20221005.151340/warp/pywarp90'
2022-10-05T15:13:39Z install_main
Unexpected error; Install failed.
```

What error are you seeing on the failure?

**Comment by e-carlin** [comment]
>  I saw this error(warning)

I see that as well

> What error are you seeing on the failure?

```
  File "build3parallel/bdist.linux-x86_64/egg/warp_parallel/__init__.py", line 336
    print ss
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(ss)?

zip_safe flag not set; analyzing archive contents...
creating 'dist/warp-4.5-py3.7.egg' and adding 'build3parallel/bdist.linux-x86_64/egg' to it
removing 'build3parallel/bdist.linux-x86_64/egg' (and everything under it)
Processing warp-4.5-py3.7.egg
Removing /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/warp-4.5-py3.7.egg
Copying warp-4.5-py3.7.egg to /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages
Removing warp 4.5 from easy-install.pth file
Adding warp 4.5 to easy-install.pth file

Installed /home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/warp-4.5-py3.7.egg
Processing dependencies for warp==4.5
Finished processing dependencies for warp==4.5
make[1]: Leaving directory '/home/vagrant/src/radiasoft/codes/warp-20221005.154252/warp/pywarp90'
2022-10-05T15:42:50Z install_main
Unexpected error; Install failed.
If you don't know what to do, please contact support@radiasoft.net.
```

There is something odd happening. For example, I don't see the line `running install_egg_info` appear anywhere in my output. 

If you search for "SyntaxError" do you see any mentions?

[Here is the full build log](https://github.com/radiasoft/download/files/9717280/warp-build.log)

**Comment by robnagler** [comment]
I do not see this. I don't know why the build is failing, but don't want to debug f32 in my dev env unnecesssarily.

>  File "build3parallel/bdist.linux-x86_64/egg/warp_parallel/__init__.py", line 336
>    print ss

Something is wrong. The installed version doesn't have this. Are you sure you are building commit 4ebb54f21373d41b8b1abe2f7a6011896324907f? 


Was this a f32 or f36 build? (Seems like f32 due to py3.7.)

We could restrict the install to avoid these issues.

**Comment by e-carlin** [comment]
When you say "installed version" you mean rscode-warp.rpm available from depot? If so, from what I can surmise that was not built from 4ebb54f21373d41b8b1abe2f7a6011896324907f .

Something is definitely wrong. Because that `print ss` is on bitbucket https://bitbucket.org/radiasoft/warp/src/4ebb54f21373d41b8b1abe2f7a6011896324907f/scripts/warp_parallel/__init__.py#lines-336

This was an f32 build. 

> We could restrict the install to avoid these issues.

Will that work? Files we definitely need installed (ex https://bitbucket.org/radiasoft/warp/src/4ebb54f21373d41b8b1abe2f7a6011896324907f/scripts/init_tools/generic_tools.py#lines-226 ) have non print_function prints.

**Comment by robnagler** [comment]
> When you say "installed version" you mean rscode-warp.rpm available from depot? If so, from what I can surmise that was not built from 4ebb54f21373d41b8b1abe2f7a6011896324907f .

```sh
$ rpm -qi rscode-warp
Name        : rscode-warp
Version     : 20201231.175726
Release     : 1
Architecture: x86_64
Install Date: Fri 29 Jan 2021 02:47:43 AM UTC
Group       : Development/Tools
Size        : 52891524
License     : none
Signature   : (none)
Source RPM  : rscode-warp-20201231.175726-1.src.rpm
Build Date  : Thu 31 Dec 2020 06:14:16 PM UTC
Build Host  : fnl1b.bivio.biz
URL         : none
Summary     : version: 4ebb54f21373d41b8b1abe2f7a6011896324907f
Description :
version: 4ebb54f21373d41b8b1abe2f7a6011896324907f
source: https://bitbucket.org/radiasoft/warp.git
build: /home/vagrant/src/radiasoft/codes/warp-20201231.175726/warp
$ rpm --verify rscode-warp
$
```

It's very strange.

```py
$ gcl https://bitbucket.org/radiasoft/warp.git
$ git checkout 4ebb54f21373d41b8b1abe2f7a6011896324907f
$ diff scripts/warp_parallel/__init__.py ~/.pyenv/versions/py3/lib/python3.7/site-packages/warp_parallel/__init__.py
336c336
<         print ss
---
>         print(ss)
339c339
<             print result
---
>             print(result)
343c343
<             print
---
>             print()
408c408
<         procs = range(number_of_PE(comm=comm))
---
>         procs = list(range(number_of_PE(comm=comm)))
449c449
<         procs = range(number_of_PE(comm=comm))
---
>         procs = list(range(number_of_PE(comm=comm)))
526c526
<         print "Object could not be converted to an array"
---
>         print("Object could not be converted to an array")
538c538
<         print "Error in gather object"
---
>         print("Error in gather object")
```

There were no changes to warp.sh since the rpm was built. There's nothing about patches to prints.

**Comment by robnagler** [comment]
I just went through all commits in 2020 and non has a `print(ss)` in that file. The only rscode-warp.rpm we have (from backups) is from the build on 2020-12-31, which was the only build for f32.

I cannot figure out how the print fixups got in the build.

**Comment by robnagler** [comment]
Either we did exactly the same fixes (unlikely especially `list(range`) or we had a patch from the future when the RPM was built:

```sh
$ gcl https://bitbucket.org/berkeleylab/warp
$ cd warp
$ git log scripts/warp_parallel/__init__.py
commit 263b5eac232b54fbe3541e0337925f4955476379
Author: Dave Grote <grote1@llnl.gov>
Date:   Mon Dec 13 16:20:48 2021 -0800

    Converted to Python3. Version 2 is no longer supported

commit 4d9c1357d13cb7ae3b58f25fe7af6fee61c497b5
Author: Dave Grote <dpgrote@lbl.gov>
Date:   Mon May 4 11:42:57 2020 -0700

    On NERSC, force serial if running on login nodes

commit 8bbffe905754339b86b7c7e232229846bbdc334b
Author: Dave Grote <grote1@llnl.gov>
Date:   Tue May 22 13:35:23 2018 -0700

    Permenently moved parallel and warpoptions to separate packages
$ git show 263b5eac232:scripts/warp_parallel/__init__.py | diff ~/.pyenv/versions/py3/lib/python3.7/site-packages/warp_parallel/__init__.py -
11a12,16
> import os
> if 'NERSC_HOST' in os.environ and 'SLURM_JOB_ID' not in os.environ:
>     # On NERSC login nodes, trying to import mpi4py causes a crash.
>     serial = True
>
```
