### ISSUE TITLE
20221130 h5ImageGenerator needed for ml

### ISSUE THREAD

**Issue by gurhar1133** [radiasoft/download#379]
the h5imagegenerator python package is needed for [activait image preprocessing](https://github.com/radiasoft/sirepo/issues/4995) (memory efficient batch shuffling and scaling) 

@e-carlin  brought to my attention that adding to ml installer stuff won't be an option until we have moved to fedora 36. This could take weeks.

@moellep do we want to merge [#4995](https://github.com/radiasoft/sirepo/issues/4995) sooner than that? and if so do you know of any workarounds to merge/get ci checks passing @robnagler

**Comment by moellep** [comment]
I think we'll need to delay merging the activait PR until the h5imagegenerator is available - otherwise it will fail on alpha. We could keep working off that branch until it is available.

**Comment by e-carlin** [comment]
To add some color: ml.sh changed in the migration to fedora 36 so now the rpm can't be built for fedora 32. So, this fix is blocked until we finish the fedora 36 migration. I don't have a good estimate for when that will be done. Still working through synergia issues https://github.com/radiasoft/sirepo/issues/5170. We could do some workarounds like create a new rscode that has just this dependency. That way it could be built for fedora 32.

**Comment by moellep** [comment]
Could we add h5imagegenerator to a different install script used by sirepo?

**Comment by robnagler** [comment]
> Could we add h5imagegenerator to a different install script used by sirepo?

I just had a discussion yesterday about people who are worried Sirepo has "cruft" in our Docker images. I think we should minimize dependencies in sirepo/setup.py and container-conf that are only related to template code. All that should be in beamsim, and ideally in an RPM so it's composable.

**Comment by robnagler** [comment]
@e-carlin could you put a conditional for fedora 32 & 36 in ml.sh with this dependency added in both cases? That seems like the cleanest solution. I think f36 is going on a bit longer...

**Comment by e-carlin** [comment]
Sure
