### ISSUE TITLE
container-conf access to whole repo

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#407]
Currently container-conf does a `COPY .`, but it really should do a `COPY ..`.  Not sure if we want access to `.git`, which would be pulled in. The way pksetup works, we probably do want it. The `COPY ..` could be controlled by a variable in the build.sh, which gets read before the Dockerfile is built. This is the fastest path to backward compatibility.

**Comment by e-carlin** [comment]
I think we might want the .git. In rsiviz you can pass in a branch to build.sh which I use for testing out in progress work. You'd need the .git to make the branch useful.

**Comment by robnagler** [comment]
Fix https://github.com/radiasoft/containers/commit/18502b7e6e542fafb7d836d434b6c4d29a44e2e2
