### ISSUE TITLE
geant4 installer

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#412]
https://geant4-userdoc.web.cern.ch/UsersGuides/InstallationGuide/html/gettingstarted.html#softwarerequirements

Stephen C needs it but the work isn't associated with a RS project until March so there are no hours. He was trying `spack install geant4`  in the devbox but ran into https://stackoverflow.com/questions/50785575/configuring-qtbase-fails-with-an-error-could-not-find-qmake-spec . 

Since there are no hours I did the quickest thing I could think of - exec'd into his devbox as root, ran `dnf install qt5-qtbase-devel`, `su - vagrant`, `spack install geant4`. This worked. Leaving this as a placeholder to create a real installer once there are hours.

**Comment by Kinami2022** [comment]
![image](https://user-images.githubusercontent.com/125559310/235332640-7479147d-09d7-41d6-8d8c-1727975fee70.png)
please i need help on the installation

**Comment by e-carlin** [comment]
Hi @Kinami2022, I haven't built geant4 from source so I'm not sure about that error. The steps above (`dnf install qt5-qtbase-devel` and `spack install geant4`) worked for me on Fedora 32.

You might have more luck asking the geant4 developers about your error on their [user forum](https://geant4-forum.web.cern.ch/).

**Comment by sjcrs** [comment]
I'd like the following flags ON for usability:

`GEANT4_BUILD_MULTITHREADED`, `GEANT4_INSTALL_DATA`

Note: The data installation will be about 1.5 Gb.

For the application to pop open visualizations via X11, you may need a combination of the OpenGL_X11 flags or the QT flags and those related dependencies.
