### ISSUE TITLE
nersc-pyenv update available versions

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#461]
```
python-build: definition not found: 3.9.15

See all available versions with `pyenv install --list'.

If the version you need is missing, try upgrading pyenv:

  cd /global/homes/n/<snip>/.pyenv/plugins/python-build/../.. && git pull && cd -
```

Running the supplied command and then re-running the installer worked. The `git pull` should be added to the installer.

**Comment by robnagler** [comment]
What about calling pyenv update?

**Comment by e-carlin** [comment]
That looks better. Odd they don't recommend that command instead of this one...

**Comment by robnagler** [comment]
too expensive to automate
