### ISSUE TITLE
docker 24 : failed to start daemon: unknown option overlay2.override_kernel_check: overlay2

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#477]
On Docker version 24.0.0 I'm seeing this error:

```
May 17 22:08:00 v.radia.run dockerd[15310]: failed to start daemon: error initializing graphdriver: overlay2: unknown option overlay2.override_kernel_check: overlay2
```

This is a deprecated feature https://docs.docker.com/engine/deprecated/#support-for-the-overlay2override_kernel_check-storage-option. Maybe they removed support for it in 24? Not sure but I think it can be removed.

**Comment by robnagler** [comment]
Fixed in https://github.com/radiasoft/rsconf/pull/330 but maybe also in redhat-docker
