### ISSUE TITLE
Use latest csx-tools in rscode-bluesky

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#478]
The notebooks that depend on it now expect the latest.

**Comment by rorour** [comment]
[csxhelpers branch](https://github.com/radiasoft/download/tree/csxhelpers) was created to test csx-tools changes that have yet to be merged. I think we are waiting on https://github.com/NSLS-II-CSX/csxtools/pull/89 to be merged to make this change official.

**Comment by ambarb** [comment]
I just merged this

**Comment by ambarb** [comment]
@mrakitin @hyperrealist  should we increase the version?  I don't know how to do that

**Comment by rorour** [comment]
Closing since we are now using conda env for csx
