### ISSUE TITLE
20230808 srwpy now uses main SRW repo

### ISSUE THREAD

**Issue by moellep** [radiasoft/download#487]
We can consider using pip install srwpy now, it links to the main SRW repo:

> Sirepo building procedures may need to be changed to just do pip install --pre srwpy. Also, we had to restructure the package, so that it better fits the Python's site-package structure, and now the imports need to be changed from import uti_math to from srwpy import uti_math and so on.

**Comment by robnagler** [comment]
This will break everybody's Jupyter notebooks

**Comment by robnagler** [comment]
Create stubs so that the notebooks don't break with a deprecated warning that users will see.

**Comment by robnagler** [comment]
@rorour schedule a meeting so we can discuss
