### ISSUE TITLE
`~/.pyenv/versions/py3/lib64/` in rscode-common

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#494]
I don't know that lib64 is going to be picked up by python. blosc2 is getting installed there. Must be a dependency, because I don't see what's installing it. 

This might be a red herring. Just raising as a possible issue.

**Comment by e-carlin** [comment]
```
examples (main)$ pipdeptree --reverse --packages blosc2
<snip>
------------------------------------------------------------------------
blosc2==2.0.0
└── tables==3.8.0 [requires: blosc2~=2.0.0]
```

tables is in common. 

I don't know anything about blosc2. The files definitely look to be coming from it.
```
installers (master)$ pip uninstall blosc2
Found existing installation: blosc2 2.0.0
Uninstalling blosc2-2.0.0:
  Would remove:
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/include/blosc2.h
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/include/blosc2/blosc2-common.h
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/include/blosc2/blosc2-export.h
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/include/blosc2/blosc2-stdio.h
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/include/blosc2/codecs-registry.h
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/include/blosc2/filters-registry.h
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/blosc2-2.0.0.dist-info/*
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/blosc2/*
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.a
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.so
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.so.2
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.so.2.6.1
    /home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/pkgconfig/blosc2.pc
```

I cloned their repo and ran [some of the examples](https://github.com/Blosc/python-blosc2/tree/main/examples) with the blosc2 installed from common. The ones I tried all worked. If I delete the files in lib64 the examples also work so I'm not sure what is going on. 

Since the examples work I'm going to not investigate further.

**Comment by robnagler** [comment]
I think it would be good to know where the examples are getting libblosc2 from. It might be from a global source unrelated to the install. lib64 may be a red herring. I don't know how it would find that directory to load...

**Comment by e-carlin** [comment]
> I think it would be good to know where the examples are getting libblosc2 from

Here is how I tried to answer that question:

```
/# find / -iname '*libblos*'
/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/tables/libblosc2.so
/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/tables.libs/libblosc2-84755600.so.2
/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.a
/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.so
/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.so.2
/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib64/libblosc2.so.2.6.1
```

If I remove the result in tables/ then tables errors on import. I can remove lib64 and there are no problems. 


Using strace I see:
examples (main)$ strace -e trace=open,openat -f python compress_decompress.py 2>&1 | grep -E 'blosc2'
openat(AT_FDCWD, "/home/vagrant/src/Blosc/python-blosc2/examples/compress_decompress.py", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/vagrant/src/Blosc/python-blosc2/examples/compress_decompress.py", O_RDONLY) = 3
openat(AT_FDCWD, "/home/vagrant/src/Blosc/python-blosc2/examples", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2/__pycache__/__init__.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
openat(AT_FDCWD, "/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2/blosc2_ext.cpython-39-x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 3
[pid 467834] openat(AT_FDCWD, "/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2/__pycache__/core.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[pid 467834] openat(AT_FDCWD, "/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2/__pycache__/SChunk.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
[pid 467834] openat(AT_FDCWD, "/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2/__pycache__/version.cpython-39.pyc", O_RDONLY|O_CLOEXEC) = 3
```

My guess is it is getting blosc2 from `/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2/blosc2_ext.cpython-39-x86_64-linux-gnu.so`. If I remove that file blosc2 errors on import. 

```
examples (main)$ python -c 'import blosc2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.9/site-packages/blosc2/__init__.py", line 44, in <module>
    from .blosc2_ext import (
ModuleNotFoundError: No module named 'blosc2.blosc2_ext'
```


From the [c-blosc docs](https://github.com/Blosc/c-blosc2#python-wrapper) I see

> as a bonus, the python-blosc2 package comes with wheels and binary versions of the C-Blosc2 libraries, so anyone, even non-Python users can install C-Blosc2 binaries

So, maybe the files in lib64 are a way to distribute the binaries for non-python users?

**Comment by robnagler** [comment]
> So, maybe the files in lib64 are a way to distribute the binaries for non-python users?

Yes, that must be it. Good research, though. I think, unfortunately, we have to diagnose these things.

https://github.com/radiasoft/download/issues/508
