### ISSUE TITLE
Add warpx and pywarpx to the Jupyter container

### ISSUE THREAD

**Issue by ncook882** [radiasoft/download#504]
Following up on the previous [issue](https://github.com/radiasoft/rsfusion/issues/2)

The installation should support all dimensions (1,2,3,RZ). Our plan is to run various configurations via rsmpi.

**Comment by robnagler** [comment]
This is on production.

**Comment by ncook882** [comment]
@robnagler @e-carlin  I no longer see the WarpX executables on Jupyter. @cchall has also reported the same. Is this related to changes stemming from https://github.com/radiasoft/download/pull/682?

**Comment by e-carlin** [comment]
Probably. I'll take a look.
