### ISSUE TITLE
20240101 numpy 2.0

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#509]
Numpy 2.0 will be released in January of 2024. Details on the change and a link to a project board tracking issues can be found [here](https://hackmd.io/@seberg/Bk5P9wJuj).

In their words it is not a "break the world release". We will at least need to fix warp and gist use of `from numpy import *` https://github.com/numpy/numpy/pull/24234 (unless they do it first).

I imagine they will have release candidates which would be good to test against.

**Comment by e-carlin** [comment]
The release has been delayed but is approaching https://mail.python.org/archives/list/python-announce-list@python.org/thread/EGXPH26NYW3YSOFHKPIW2WUH5IK2DC6J/ .

Looks like they are shooting for sometime in the next month to 8 weeks https://github.com/numpy/numpy/issues/24300#issuecomment-1986815755 .

I need to put more thought into this but I'm inclined to try pinning numpy<2.0 for "some time". Let changes to numpy settle out and let maintainers of dependent packages update their code. 

Deps like tensorflow have taken this approach https://github.com/tensorflow/tensorflow/blob/v2.15.0/tensorflow/tools/pip_package/setup.py#L93 . I don't know which codes of ours depend on numpy but my guess is many that have a python component. I also don't know which codes depend on the C ABI but those will need to be recompiled because of the ABI break.

At the very least warp will need to be fixed due to the changes in `from numpy import *`.  https://github.com/radiasoft/download/pull/503

@robnagler I'd like your thoughts.

**Comment by robnagler** [comment]
Yes, let's pin. There's no point in moving on. We also have the SQLAlchemy 2.0 to consider...
