### ISSUE TITLE
warpx installer for nersc

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#530]
@bruhwiler writes:
> To execute on GPUs, I think the easiest thing will be to follow the WarpX build instructions for NERSC.

Having an installer will make this easier for scientists.

https://warpx.readthedocs.io/en/latest/install/hpc/perlmutter.html

**Comment by robnagler** [comment]
Perlmutter instructions are different. 

However, new WarpX requires -DWarpX_PYTHON=ON. Need to modify codes/warpx.sh

**Comment by ax3l** [comment]
Feel free to ping me if you need any help on this. The link above is the right location to follow, we regularly update the instructions in lock-step with the system changes.

**Comment by ax3l** [comment]
Cool, great to hear! :tada:
