### ISSUE TITLE
dev-build.sh: line 15: cd: /home/vagrant/src/radiasoft/container-rpm-code: No such file or directory

### ISSUE THREAD

**Issue by rorour** [radiasoft/download#555]
I got the following error running rpm-code/dev-build.sh (after the script had already been running for 30 minutes)

`dev-build.sh: line 15: cd: /home/vagrant/src/radiasoft/container-rpm-code: No such file or directory
`

Maybe we should assert that `container-rpm-code` and `container-fedora` exist at the beginning, or gcl if they don't exist yet.

**Comment by robnagler** [comment]
An assertion would be fine to tell people they have to run dev-server.sh. The README documents this.
