### ISSUE TITLE
flash-tarball update version

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#572]
Need to run tests to ensure that the version is compatible with various packages we are using.

**Comment by e-carlin** [comment]
> Need to run tests to ensure that the version is compatible with various packages we are using.

We've run the sirepo.com/flash examples. Are there other tests that should be run?

**Comment by robnagler** [comment]
@ncook882 said something about not being sure all his configs will work with the latest code. He also said "we could just release it and see". Maybe once it is on alpha, he can test his configs.
