### ISSUE TITLE
remove flash problem files?

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#574]
We bundle the CapLaser3D and CapLaserBELLA problem files with the flash tarball. I believe this was done in the past when we had an example for each. But, with the way flash works currently I think they will be generated and we don't have a CapLaser3D or CapLaserBELLA example so I think they can be removed.

**Comment by moellep** [comment]
Yes, if we no longer have CapLaser examples, the problem files don't need to be included in the tarball.
