### ISSUE TITLE
vagrant-dev on centos7

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#588]
Create installer for a vagrant-sirepo-dev vm on centos7

**Comment by e-carlin** [comment]
Removed the need for libvirt. I ran into too many issues setting it up. I didn't use virtualbox initially but the reasoning now escapes me. I just installed using virtualbox and it worked fine. 

So, all we need is to do is remove setting up a private_network (we are going to use ssh forwarding) and set the right box for centos

**Comment by robnagler** [comment]
I think we want the private network so the boxes can talk to each other if we want to support rsconf dev. If we don't, then not having the network may avoid problems we had with network collisions in the past.

**Comment by e-carlin** [comment]
As a first pass I'm going to skip supporting rsconf dev
