### ISSUE TITLE
Create installer for centos vm_devbox

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#592]
After some playing with the code I've decided that creating a dedicated vm_devbox installer would make sense.

It will call the vagrant-sirepo-dev installer with some changes:
- Default the necessary params (ex vagrant_dev_no_nfs_src)
- Setup forwarded_port. This will enable the ssh connection from the outside world to the vm. It will look like `config.vm.network "forwarded_port", guest: $guest_port, host: $host_port, host_ip: $host_ip`. The variables will be configured by rsconf and set as args to the installer. We might not need to configure guest_ip. 22 or a default non-standard port will probably work. Leave it as config for now to make it easy to change in the future in case it does matter what the guest_port. I'll need to figure out $host_ip as I work but it will probably be the public ip of the host. We may want end up binding to 127.0.0.1 and have ip tables route between the public ip:port and $host_ip:$host_port. Again leave as config in case this changes. rsconf will then configure iptables to accept connections from the internet.
- rsconf will create the ssh config file as well as the public key. It will leave them in a known location on the host that the installer will be aware of. The installer will then upload the files to the vm and restart the sshd. I think this provides the best way of having rsconf aware of configuration (ex so it can `vagrant reload` when things change) while creating an easy way to get the config into the vm. 

I considered having rsconf just generate the full Vagrantfile and not use an installer at all. In some ways this would be easier. But, I think it is nice to use our installer infrastructure. It already has many learned lessons about how to build the vms that would have to be copied to rsconf. Likewise, by using it we will continue to test the installer way of creating a vm and hopefully not reach a divergent place where the rsconf Vagrantfile works but the installer doesn't work.

**Comment by robnagler** [comment]
I think you will need to set up iptables for the forwarded port.

**Comment by e-carlin** [comment]
superceded by https://github.com/radiasoft/download/issues/598
