### ISSUE TITLE
on vm devbox slurm install prints incorrect error

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#620]
We run slurm locally. Also the number of cpus may be incorrect (or might be ok). I set it manually to two just now.

```txt
on v.radia.run you need to:

dnf install -y nfs-utils
cat << EOF > /etc/exports.d/home_vagrant.exports
/home/vagrant 10.10.10.0/24(rw,root_squash,no_subtree_check,async,secure)
EOF
systemctl enable nfs-server
systemctl restart nfs-server
```

Gets after slurm is installed:

`py.error.ENOENT: [No such file or directory]: open('/home/vagrant/.ssh/known_hosts', 'r')`

Then there's the key problem. We need to come up with a key that's encrypted with a passphrase that we can configure for things like sbatch_test.

I suspect docker needs to be installed, too

**Comment by e-carlin** [comment]
Do you remember why we added NFS (9123d5b3c63cfc4580ac49f3f42005fb8d274ad7)? I'm thinking about fixing this problem by removing all traces of it. In the normal development case we don't use it and since we haven't solved the multiple vm problem for vm_devbox it would be tricky to solve.

**Comment by robnagler** [comment]
It's necessary if you are running multihost slurm. This was certainly tested on local VMs when we were developing Slurm support.

You could change the default so that it doesn't configure NFS. We probably do need to solve the multihost problem, because we really should have the ability to test multihost slurm in dev.
