### ISSUE TITLE
Add bmad code to beamsim codes

### ISSUE THREAD

**Issue by moellep** [radiasoft/download#631]
https://www.classe.cornell.edu/bmad/

**Comment by robnagler** [comment]
@moellep do you want all of these? (note the f77_to_f90, which you probably don't want)

- [ ] beam_file_translate_format
- [ ] bmad_to_astra
- [ ] bmad_to_blender
- [ ] bmad_to_csrtrack
- [ ] bmad_to_gpt
- [ ] bmad_to_mad_sad_elegant
- [ ] bmad_to_merlin
- [ ] bmad_to_slicktrack
- [ ] cartesian_map_fit
- [ ] compare_tracking_methods_plot
- [ ] compare_tracking_methods_text
- [ ] controller_response_plot
- [ ] element_attributes
- [ ] errors_mad_to_bmad
- [ ] f77_to_f90
- [ ] generalized_gradient_fit
- [ ] ibs_ring
- [ ] lattice_cleaner
- [ ] lux
- [ ] mais_ripken
- [ ] make_a_matching_knob
- [ ] photon_init_plot
- [ ] photon_surface_data
- [ ] ptc_flat_file_to_bmad
- [ ] ptc_profiler
- [ ] sad_to_bmad_postprocess
- [ ] sodom2
- [ ] synrad
- [ ] synrad3d
- [ ] synrad_aperture_to_wall
- [ ] tune_plane_res_plot
- [ ] wake_fit

And these tests?

- [ ] abs_time_test
- [ ] analysis_test
- [ ] aperture_test
- [ ] autoscale_test
- [ ] backwards_time_track_test
- [ ] bbu_test
- [ ] beam_test
- [ ] bookkeeper_test
- [ ] cathode_sc_test
- [ ] closed_orbit_test
- [ ] coord_test
- [ ] csr_and_space_charge_test
- [ ] em_field_test
- [ ] field_test
- [ ] fringe_test
- [ ] geometry_test
- [ ] girder_test
- [ ] hdf5_test
- [ ] mad_to_bmad_test
- [ ] mat6_calc_method_test
- [ ] match_test
- [ ] mode3_test
- [ ] mode_flip_test
- [ ] multipass_test
- [ ] multipole_test
- [ ] nonlin_test
- [ ] object_test
- [ ] parse_test
- [ ] particle_species_test
- [ ] patch_test
- [ ] photon_test
- [ ] ptc_test
- [ ] radiation_test
- [ ] reverse_test
- [ ] sad_test
- [ ] sim_utils_test
- [ ] slice_test
- [ ] space_charge_test
- [ ] spin_general_test
- [ ] spin_map_test
- [ ] superimpose_test
- [ ] synrad3d_test
- [ ] taylor_test
- [ ] time_runge_kutta_test
- [ ] tracking_method_test
- [ ] twiss_track_test
- [ ] wake_test
- [ ] wall3d_test
- [ ] write_bmad_test
- [ ] xraylib_test

**Comment by robnagler** [comment]
@moellep there are more. I need to rebuild to find them. In particular, tao needs to be there.

**Comment by robnagler** [comment]
Here's an updated list. So you want `tao` and `bmad_to_astra` only?

- bbu
- beam_file_translate_format
- beam_track_example
- bmad_to_astra
- bmad_to_blender
- bmad_to_csrtrack
- bmad_to_gpt
- bmad_to_mad_sad_elegant
- bmad_to_merlin
- bmad_to_opal_example
- bmad_to_slicktrack
- cartesian_map_fit
- compare_tracking_methods_plot
- compare_tracking_methods_text
- construct_taylor_map
- controller_response_plot
- csr_example
- dark_current_tracker
- dispersion_simulation
- dynamic_aperture
- e_cooling
- element_attributes
- em_field_query_example
- envelope_ibs
- errors_mad_to_bmad
- f77_to_f90
- frequency_map
- generalized_gradient_fit
- ibs_linac
- ibs_ring
- lapack_examples
- lattice_cleaner
- lattice_geometry_example
- long_term_tracking
- lux
- mais_ripken
- make_a_matching_knob
- multi_turn_tracking_example
- particle_track_example
- photon_init_plot
- photon_surface_data
- plot_example
- ptc_flat_file_to_bmad
- ptc_layout_example
- ptc_profiler
- ptc_spin_orbital_normal_form
- sad_to_bmad_postprocess
- simple_bmad_program
- sodom2
- spin_amplitude_dependent_tune
- spin_matching
- spin_stroboscope
- srdt_lsq_soln
- synrad
- synrad3d
- synrad_aperture_to_wall
- tao
- tune_plane_res_plot
- tune_scan
- wake_fit
- wall_generator

**Comment by moellep** [comment]
Yes tao and bmad_to_astra

And add dynamic_aperture.

Probably only tao is important.
