### ISSUE TITLE
epics libraries need to be installed?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#68]
@moellep writes:

When I try running epics with the latest install from radia_run, I get the error below:

```sh
$ beam_line_example epics-boot.cmd
beam_line_example: error while loading shared libraries: libqsrv.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by robnagler** [comment]
I can't find beam_line_example other than .db and .dbd. Is there a binary somewhere? If so, it needs to be compiled with epics, because we build statically to avoid LD_LIBRARY_PATH problems.

**Comment by robnagler** [comment]
@j-edelen @moellep I poked around at this, and learned some about EPICS, which generally assumes it is being executed out of its build directory. Even when you set EPICS_BASE, it complains:

```txt
Warning: IOC is booting with TOP = "."
          but was built with TOP = "/home/vagrant/tmp/rjn"
```

Epics "base" will be built in `~/.local/epics/base`. The programs (not libraries) will be relocated to `~/.local/bin`.

`beam_line_example` will be renamed to `epics_sirepo`, since it will be in a global name space. I will also create a separate repo for the code, since rscon has a bunch of other stuff in it that is irrelevant to the build and maintenance of the code.

I see how the cmd stuff works, too, and how we are using it. I'm guessing we'll be able to create new dbd files for each example. Also, I don't think anything in sirepo uses `fodo_program` or  `sirepo_epics_connector`. The only program used that I see is `beam_line_example`. Please let me know if I'm missing something.

**Comment by moellep** [comment]
Yes, I think the beam_line_example (now epics_sirepo) is the only executable outside of epics which needs to be included. I saw the "booting with Top" warning in the past but the program seems to run OK.

**Comment by robnagler** [comment]
I think the warning is irrelevant to the program's operation (didn't see reference in elsewhere in the code to the variable being checked) except that if the program was started with a differing LD_LIBRARY_PATH or the RPATH's point to a different version. I think EPICS goes to great lengths to hardware paths to avoid this problem (e.g. by setting RPATH in binaries).

**Comment by robnagler** [comment]
The epics command is softIoc that replaces beam_line_example. I've got to run the build to fix it so the program works, and checkin some commits for sirepo.

**Comment by robnagler** [comment]
While building, I've looked at pvput to try to figure out how it works. We will need to run a client provider, which is a separate server. This provider is a registry where clients can register. They give themselves a name. The default is "pva". Not worth our time to set this up for this example.

**Comment by robnagler** [comment]
@moellep @j-edelen @mkeilman please run in your Fedora 29 VMs:

```sh
radia_run  sirepo-dev
```

This will update rscode-epics, and all the other codes. 

`~/.local/epics` is EPICS_BASE, which is where it was compiled so everything should be copacetic with finding libraries and dbd files.

The Jupyter image has not been rebuilt. I want to wait before doing that, because there are a lot of changes that need testing.
