### ISSUE TITLE
Add python support to ImpactX build

### ISSUE THREAD

**Issue by moellep** [radiasoft/download#680]
We'll need the "impactx" python library as well. I think that gets added with -DImpactX_PYTHON=ON.

**Comment by moellep** [comment]
Also double check that the python bindings works after the build - some people haven't been able to get it to work when building locally.

**Comment by ax3l** [comment]
Hi @cchall, can you point me to the build script? I think this might just be a small version mismatch of some kind in dependencies.

**Comment by ax3l** [comment]
> Also double check that the python bindings works after the build - some people haven't been able to get it to work when building locally.

@moellep oh no, let me know where people got stuck please.

I will reduce the info in the ImpactX readme file. The recommended install docs are:
- pre-compiled packages: https://impactx.readthedocs.io/en/latest/install/users.html
- developer build: https://impactx.readthedocs.io/en/latest/install/cmake.html

**Comment by cchall** [comment]
@ax3l I just followed the developer build commands

> cmake -S . -B build -DImpactX_PYTHON=ON
> cmake --build build -j 4

I tried repeating this after clearing out build. It looks like amrex version 24.04 is should be used, which I think was released right after the commit you pointed to. I noticed that previously the impactx import was not pointing to the version in build/. However, I still get the same error:

```
In [3]: import impactx
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 import impactx

File ~/jupyter/repos/impactx/build/lib/site-packages/impactx/__init__.py:20
     17             os.add_dll_directory(p_abs)
     19 # import core bindings to C++
---> 20 from . import impactx_pybind as cxx
     21 from .extensions.ImpactXParIter import register_ImpactXParIter_extension
     22 from .extensions.ImpactXParticleContainer import (
     23     register_ImpactXParticleContainer_extension,
     24 )

ImportError: /home/vagrant/jupyter/repos/impactx/build/lib/site-packages/impactx/impactx_pybind.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN5amrex12FabArrayBase20m_alloc_single_chunkE
```

I've attached the full log. It's also certainly possible that there might be an older version of amrex in our environment that is being grabbed. 
[impactx.log](https://github.com/radiasoft/download/files/15424640/impactx.log)

**Comment by ax3l** [comment]
Hi @cchall ,

I think I see what this does from #677 now.

You want to add something like
```
codes_dependencies common
codes_dependencies amrex
codes_dependencies pyamrex
codes_dependencies openpmd-api
...
codes_cmake2 \
  -DCMAKE_INSTALL_PREFIX="${codes_dir[prefix]}" \
  -DImpactX_amrex_internal=OFF  \
  -DImpactX_pyamrex_internal=OFF
```

to disable the ImpactX superbuilds and rely on a shared external amrex library.
https://impactx.readthedocs.io/en/latest/install/cmake.html#compile

Also, a pyamrex package will be needed that also depends on amrex.

**Comment by ax3l** [comment]
Just FYI, this is the BLAST Exascale software stack. Elements on top depend on elements below them.
![image](https://github.com/radiasoft/download/assets/1353258/594f6bbb-2e9d-4ff7-a618-b5ef5ffd8727)

If you only deploy ImpactX, ignore in situ visualization, ABLASTR, PICSAR-QED, and Lin. Alg. for now.
FFT (FFTW on CPU, CUDA/HIP ship cuFFT/rocFFT for GPU) will be part of the ImpactX dependencies in 24.05+ (for our IGF Poisson solver).

If it is easier for you to read other package managers, here are our conda recipes:
- [AMReX](https://github.com/conda-forge/amrex-feedstock/blob/main/recipe/meta.yaml)
- [pyAMReX](https://github.com/conda-forge/pyamrex-feedstock/blob/main/recipe/meta.yaml)
- [ImpactX](https://github.com/conda-forge/impactx-feedstock/blob/main/recipe/meta.yaml)

**Comment by ax3l** [comment]
I added some suggestions in #682, but I do not know how to test this (help welcome :) )

**Comment by e-carlin** [comment]
Fixed by https://github.com/radiasoft/download/pull/682
