### ISSUE TITLE
Getting Error: Unable to find a match: opendkim-tools

### ISSUE THREAD

**Issue by StaticYolt** [radiasoft/download#687]
Following the Vagrant tutorial: https://github.com/radiasoft/sirepo/wiki/Development

I got up to the step where you type in this command: curl https://radia.run | bash -s redhat-dev

I am on Linux Ubuntu Debian

**Comment by robnagler** [comment]
@StaticYolt which version of fedora are you using? I updated the instructions to use the generic/fedora36 box the Vagrantfile. Perhaps try that.

**Comment by StaticYolt** [comment]
I was using the cloud fedora 32 but I think the updated version works. By works I mean that the dependencies like opendkim tools were there.

**Comment by StaticYolt** [comment]
Thanks!

**Comment by robnagler** [comment]
Glad it works. I apologize for not updating the README.
