### ISSUE TITLE
missing warpx executables

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#688]
cc: @ncook882

https://github.com/radiasoft/download/issues/504#issuecomment-2161084870

**Comment by e-carlin** [comment]
Looks like they were dropped in july of 2023
```
# for f in /srv/depot/srv/yum/fedora/36/x86_64/dev/rscode-warpx*.rpm; do
    echo "rpm=$f"
    rpm -qlp "$f" | grep -i 'bin/warpx'
    echo
done

rpm=/srv/depot/srv/yum/fedora/36/x86_64/dev/rscode-warpx-20230715.204520-1.x86_64.rpm
/home/vagrant/.local/bin/warpx.1d.MPI.OMP.DP.PDP.OPMD.QED
/home/vagrant/.local/bin/warpx.2d.MPI.OMP.DP.PDP.OPMD.QED
/home/vagrant/.local/bin/warpx.3d.MPI.OMP.DP.PDP.OPMD.QED
/home/vagrant/.local/bin/warpx.rz.MPI.OMP.DP.PDP.OPMD.QED

rpm=/srv/depot/srv/yum/fedora/36/x86_64/dev/rscode-warpx-20231213.211554-1.x86_64.rpm

rpm=/srv/depot/srv/yum/fedora/36/x86_64/dev/rscode-warpx-20240604.214425-1.x86_64.rpm
```

**Comment by e-carlin** [comment]
@robnagler building warpx executables was turned off in [this commit](https://github.com/radiasoft/download/commit/1ffe2d17bcf3e2b2ade0a1b109496d906d2e452f) (added `-D WarpX_APP=OFF`). Was there a reason?

**Comment by robnagler** [comment]
Probably because we were having trouble building and @ncook882 said we only needed the Python, and I was trying to get WarpX in the release.

**Comment by e-carlin** [comment]
Thanks. I'll try to add them back in.

**Comment by e-carlin** [comment]
Blocked by https://github.com/ECP-WarpX/impactx/issues/634 . There are ways to work around the problem but I'm going to see if we can get the fix in impactx so we don't have to.

**Comment by ax3l** [comment]
Let me know if you like to take this up again or need help. There are easy ways to install WarpX and ImpactX side by side with minimal work-arounding until the above features are implemented.

For example, see our conda package for blast-codes:
- https://github.com/conda-forge/blast-codes-feedstock/tree/main/recipe
- https://github.com/conda-forge/warpx-feedstock/blob/fe333a9a2aed24b18268f60f895351d3968d95bf/recipe/build.sh#L49-L65
- https://github.com/conda-forge/impactx-feedstock/blob/39806f5bfdbf313dfc867d7044c219b484ad6603/recipe/build.sh#L47-L54

**Comment by e-carlin** [comment]
Thanks @ax3l! Removing the static libraries works for us for now.

**Comment by ax3l** [comment]
Awesome, glad to help.
