### ISSUE TITLE
all install_vars_export's need an eval in front of them

### ISSUE THREAD

**Issue by e-carlin** [radiasoft/download#706]
I'm running into environment not being cascaded properly. Specifically, [here](https://github.com/radiasoft/download/blob/8aff0bd9b6ce80ae2026594e17c85a16fe09cb76/installers/vagrant-dev/radiasoft-download.sh#L192). In that case install_version_centos is set to the default even if I set it when calling the installer. `install_vars_export` echo's out the declare statements which I think we need to then eval. So, the code should be changed to `eval  $(install_vars_export)`. 

We [eval in this case](https://github.com/radiasoft/download/blob/8aff0bd9b6ce80ae2026594e17c85a16fe09cb76/bin/install.sh#L209). But, not in [every other case](https://github.com/search?type=code&q=user%3Aradiasoft+install_vars_export). Maybe they're all broken too? I haven't looked closely at any of the cases besides the one in vagrant-dev.

@robnagler can you confirm that eval should be added to all calls to install_vars_export?

**Comment by e-carlin** [comment]
Figured it out.  Confusion between evaluation and execution. The call to install_vars_export becomes all of the declare statements when evaluated. They then get executed when the ssh command is executed. Just need to add install_version_centos to the list of variables in install_vars_export.

**Comment by robnagler** [comment]
Maybe document that you have to do this at the point the vars are declared.
