### ISSUE TITLE
Add mayavi to py2 in beamsim-jupyter

### ISSUE THREAD

**Issue by robnagler** [radiasoft/download#72]
@moellep writes:

I made a wiki for installing mayavi on the dev vm.

https://github.com/radiasoft/devops/wiki/Mayavi-Install

We need this for comparing plots from rswarp (which uses mayavi for the examples) against sirepo vtk.js.

I was able to get it working in the py3 env, but we actually need it for py2 to test with warp  (rswarp/examples/visualization/impact_density_3d.py for example).

I tried getting something working with pyenv py2, but without success. Rob, could you give it a try for py2? A bonus would be if it also works with jupyter notebooks.

**Comment by moellep** [comment]
Do we want this in beamsim, or as a separate item? It is only needed on dev and I think it will really bloat beamsim (vtk, qt5, etc).

**Comment by robnagler** [comment]
You said you want it to work with jupyter notebooks and dev. That kind of means "beamsim-codes", but it doesn't have to be. Let me see how big it is when built.

**Comment by moellep** [comment]
It could be just jupyter notebooks run on dev, not on the jupyter servers. Unless someone else requests it.

**Comment by robnagler** [comment]
Mayavi doesn't work with Jupyter even though [it says it does](http://docs.enthought.com/mayavi/mayavi/tips.html#off-screen-rendering). The problem is that it needs X11 to be running in some form, which means starting [Xvfb](http://docs.enthought.com/mayavi/mayavi/tips.html#rendering-using-the-virtual-framebuffer). That's not a realistic option.

@cchall I do not think Mayavi is the best choice. There must be a another way to render these graphs directly in Jupyter. What about:

* [k3d-jupyter](https://opendreamkit.org/2018/10/28/3d/)
* [plotly](https://plot.ly/python/ipython-notebook-tutorial/#3d-plotting)
* [ipyvolume](https://mybinder.org/v2/gh/maartenbreddels/ipyvolume/master?filepath=notebooks/simple.ipynb) [in binder so a bit slow]

**Comment by cchall** [comment]
plotly looks like it may be able to do what we need. However, when I try to display a plot I just get a blank output in both Py2 and Py3 notebooks.

**Comment by robnagler** [comment]
I can help debug. Tell me what notebook and what prerequisites.

**Comment by cchall** [comment]
I am trying one of their examples:
import plotly.graph_objects as go

> fig = go.Figure(data=[
>     go.Mesh3d(
>         x=[0, 1, 2, 0],
>         y=[0, 0, 1, 2],
>         z=[0, 2, 0, 1],
>         colorbar_title='z',
>         colorscale=[[0, 'gold'], 
>                     [0.5, 'mediumturquoise'], 
>                     [1, 'magenta']],
>         # Intensity of each vertex, which will be interpolated and color-coded
>         intensity=[0, 0.33, 0.66, 1],
>         # i, j and k give the vertices of triangles
>         # here we represent the 4 triangles of the tetrahedron surface
>         i=[0, 0, 0, 1],
>         j=[1, 2, 3, 2],
>         k=[2, 3, 1, 3],
>         name='y',
>         showscale=True
>     )
> ])
> 
> fig.show()

I have it in a notebook 'plotly_test' in my home directory.

**Comment by cchall** [comment]
It looks like k3d may also not be working in Jupyterlab for now:
https://github.com/K3D-tools/K3D-jupyter/issues/178

**Comment by robnagler** [comment]
I got it to work by installing the jupyter lab extensions for plotly. I'll build a new image tonight (after @moellep runs a sirepo release) and then release to alpha/beta so you can test.

**Comment by robnagler** [comment]
ipywidgets seems to be broken. I need to debug. The build will have to wait till tomorrow.

**Comment by robnagler** [comment]
Doing an alpha release now. `import warp` was broken, too. They seem to be changing the way config is read, and the documentation hasn't caught up. Doing an alpha release now.

**Comment by robnagler** [comment]
@cchall please try beta-jupyter.radiasoft.org.  It has plotly built in. `import warp` now works, too. If it works for you, I'll move to prod.

**Comment by cchall** [comment]
Plotly appears to be working. Warp as well.
